### ISSUE TITLE
Problems with download links of datasets

### ISSUE THREAD

**Issue by chenshen03** [Vijetha1/WDHT#1]
There is a problem with download links to datasets. When the download is almost finished, the network will report errors, and can not continue to download.

**Comment by chenshen03** [comment]
Can you share other download links to the dataset?

**Comment by chenshen03** [comment]
solved

**Comment by mengliu1991** [comment]
@chenshen03 
Hi, 

I wanna to know how you download the dataset? Could you provide me an effective link?
I cannot download the dataset via the link provided by the author.
